#!/usr/bin/env node
// The Garden's hover card shows a Plant's Project by its image: each Project's cover, at most 480 px
// wide (the card's 240 CSS px on a 2x screen), as static/garden/covers/<slug>.webp, and the
// thumbnails' sizes in src/lib/garden/covers.js, so the card holds the image's own proportions
// before it loads. Run it again after adding a Project or changing a cover:
//
//   node scripts/garden-covers.mjs
//
// Needs macOS's sips and cwebp (brew install webp). A cover hosted elsewhere is fetched first.
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { projects } from '../src/lib/project/project.js';

const WIDTH = 480;
const root = new URL('..', import.meta.url).pathname;
const out = join(root, 'static/garden/covers');
mkdirSync(out, { recursive: true });
const tmp = mkdtempSync(join(tmpdir(), 'garden-covers-'));
process.on('exit', () => rmSync(tmp, { recursive: true, force: true }));

/** @param {string} file */
const size = (file) => {
	const info = execFileSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', file], { encoding: 'utf8' });
	return [+(/pixelWidth: (\d+)/.exec(info)?.[1] ?? 0), +(/pixelHeight: (\d+)/.exec(info)?.[1] ?? 0)];
};

/** @type {Record<string, [number, number]>} */
const sizes = {};
for (const { slug, projectImgSource: source } of projects) {
	let file = join(root, 'static', decodeURI(source));
	if (/^https?:/.test(source)) {
		const response = await fetch(source);
		if (!response.ok) throw new Error(`${slug}: ${source} answered ${response.status}`);
		file = join(tmp, `${slug}-source`);
		writeFileSync(file, Buffer.from(await response.arrayBuffer()));
	}
	const png = join(tmp, `${slug}.png`);
	const resize = size(file)[0] > WIDTH ? ['--resampleWidth', String(WIDTH)] : [];
	execFileSync('sips', ['-s', 'format', 'png', ...resize, file, '--out', png], { stdio: 'ignore' });
	execFileSync('cwebp', ['-quiet', '-q', '82', '-m', '6', png, '-o', join(out, `${slug}.webp`)]);
	sizes[slug] = /** @type {[number, number]} */ (size(png));
	console.log(`${slug}: ${sizes[slug].join('×')}`);
}

writeFileSync(
	join(root, 'src/lib/garden/covers.js'),
	`// Generated by scripts/garden-covers.mjs: each Project's cover thumbnail (static/garden/covers/<slug>.webp),
// [width, height] in px, so the Garden's hover card keeps the image's proportions before it loads.
/** @type {Record<string, [number, number]>} */
export const covers = {
${Object.entries(sizes)
	.map(([slug, [w, h]]) => `\t'${slug}': [${w}, ${h}]`)
	.join(',\n')}
};
`
);
