/**
 * Everything Gordon says in the contact chat, each line in thirty wordings. Every visit draws one
 * of each, so the chat doesn't read the same twice. They sound like him at work: plain words,
 * friendly, to the point. The first wording of each is the one the page is prerendered with.
 */

/** "1–2 days" kept on one line: a word joiner after the dash, a no-break space before "days". */
const DAYS = '1–⁠2 days';

export const lines = {
	/** Hello, and the first question: the visitor's name. */
	hello: [
		'Hey! I’m Gordon. What should I call you?',
		'Hi, I’m Gordon. What’s your name?',
		'Hey there, I’m Gordon. Who am I talking to?',
		'Hi! Gordon here. What should I call you?',
		'Hello, I’m Gordon. What’s your name?',
		'Hey, Gordon here. Who am I chatting with?',
		'Hi there! I’m Gordon. And you are?',
		'Hey! I’m Gordon. What’s your name?',
		'Hi, Gordon here. What should I call you?',
		'Hello! I’m Gordon. Who am I talking to?',
		'Hey, I’m Gordon. First things first: what’s your name?',
		'Hi! I’m Gordon. Mind telling me your name?',
		'Hey there! Gordon here. What’s your name?',
		'Hi, I’m Gordon. What name should I use for you?',
		'Hello there, I’m Gordon. What should I call you?',
		'Hey! Gordon here. Who am I talking to today?',
		'Hi, I’m Gordon. Thanks for stopping by. What’s your name?',
		'Hey, thanks for dropping in. I’m Gordon. What’s your name?',
		'Hi there, I’m Gordon. What do people call you?',
		'Hello! Gordon here. What should I call you?',
		'Hey! I’m Gordon. Let’s start with names. What’s yours?',
		'Hi! I’m Gordon. And your name is?',
		'Hey, I’m Gordon. Who’s on the other side of the screen?',
		'Hi there! I’m Gordon. What name do you go by?',
		'Hello, Gordon here. Mind sharing your name?',
		'Hey! I’m Gordon, glad you’re here. What’s your name?',
		'Hi, I’m Gordon. Before anything else, what’s your name?',
		'Hey there, I’m Gordon. What should I call you?',
		'Hi! Gordon here. Who am I chatting with?',
		'Hello! I’m Gordon. Can I get your name?'
	],

	/** @type {((name: string) => string)[]} */
	meet: [
		(name) => `Nice to meet you, ${name}!`,
		(name) => `Great to meet you, ${name}!`,
		(name) => `Hi ${name}, nice to meet you!`,
		(name) => `Good to meet you, ${name}.`,
		(name) => `Hey ${name}, great to have you here.`,
		(name) => `Thanks, ${name}. Nice to meet you!`,
		(name) => `Lovely to meet you, ${name}!`,
		(name) => `Hi ${name}! Glad you stopped by.`,
		(name) => `Nice to meet you, ${name}. Thanks for reaching out!`,
		(name) => `Great to meet you, ${name}. Thanks for saying hi.`,
		(name) => `Hey ${name}! Nice to meet you.`,
		(name) => `${name}, nice to meet you!`,
		(name) => `Welcome, ${name}! Nice to meet you.`,
		(name) => `Good to have you here, ${name}.`,
		(name) => `Hi ${name}, thanks for dropping by!`,
		(name) => `Pleasure to meet you, ${name}!`,
		(name) => `Hey ${name}, thanks for getting in touch!`,
		(name) => `Great to meet you, ${name}! Thanks for writing.`,
		(name) => `Hi ${name}! Really glad you’re here.`,
		(name) => `Nice to meet you, ${name}. Glad you found me.`,
		(name) => `Hello ${name}, nice to meet you!`,
		(name) => `Thanks for stopping by, ${name}!`,
		(name) => `Great to have you, ${name}!`,
		(name) => `Hey ${name}! Thanks for reaching out.`,
		(name) => `Nice to meet you, ${name}. Let’s get into it.`,
		(name) => `Good to meet you, ${name}! Thanks for coming by.`,
		(name) => `Hi ${name}, great to meet you.`,
		(name) => `${name}! Great to meet you.`,
		(name) => `Hey ${name}, nice to meet you!`,
		(name) => `Glad you’re here, ${name}. Nice to meet you!`
	],

	/** The project: what the data is and who it's for. */
	about: [
		'Tell me about it. What’s the data, and who’s it for?',
		'So, what are you working on? What’s the data, and who’s it for?',
		'What’s the project? Tell me about the data and who it’s for.',
		'Tell me what you’re working on: the data, and who will use it.',
		'What are you working on? I’d love to hear about the data and the audience.',
		'So, what’s the project? What data do you have, and who’s it for?',
		'Tell me about your project. What’s the data, and who should it reach?',
		'What can I help with? Tell me about the data and who it’s for.',
		'What’s on your mind? If it’s a project, tell me about the data and who it’s for.',
		'Let’s hear it. What’s the data, and who’s it for?',
		'Tell me a bit about the project. What data are you working with, and who’s it for?',
		'What are you building? What’s the data, and who will read it?',
		'So, what’s the idea? Tell me about the data and the audience.',
		'Tell me what you have in mind. What’s the data, and who’s it for?',
		'What’s the project about? What data do you have, and who’s it for?',
		'Walk me through it. What’s the data, and who’s it for?',
		'Tell me more. What data are you working with, and who’s the audience?',
		'What would you like to make? Tell me about the data and who it’s for.',
		'Give me the short version: what’s the data, and who’s it for?',
		'What are you hoping to build? What’s the data, and who will use it?',
		'Let’s start with the project. What’s the data, and who’s it for?',
		'Tell me about the project: the data you have and the people it’s for.',
		'So what’s the plan? What data do you have, and who needs to see it?',
		'What story do you want to tell? What’s the data, and who’s it for?',
		'Tell me what you’re after. What’s the data, and who’s the audience?',
		'What are you working on? Start with the data and who it’s for.',
		'I’d love to hear about the project. What’s the data, and who’s it for?',
		'What’s the project? A few lines on the data and the audience is plenty.',
		'How can I help? If there’s a project, what’s the data and who’s it for?',
		'Tell me what brings you here. For a project: what’s the data, and who’s it for?'
	],

	/** A deadline or budget, if there is one. */
	extras: [
		'Got a deadline or a budget? Toss those in too.',
		'If there’s a deadline or budget, add that too.',
		'Deadline or budget in mind? Feel free to include it.',
		'Any timeline or budget? Drop that in as well.',
		'Got a date or a budget to work with? Mention it too.',
		'If you have a deadline or a budget, include it. It helps.',
		'Timeline and budget help too, if you have them.',
		'Working to a deadline or budget? Let me know.',
		'A deadline or rough budget helps me plan, if you have one.',
		'Any dates or budget I should know about? Add them too.',
		'Toss in a deadline or budget if you’ve got one.',
		'If there’s a launch date or budget, include that too.',
		'Deadline? Budget? Add them if you know them.',
		'A rough budget or timeline is useful too, if you have one.',
		'Let me know about any deadline or budget as well.',
		'Got a due date or budget? Throw that in too.',
		'If timing or budget matters, mention it.',
		'Any deadline or budget? No worries if not yet.',
		'Include a deadline or budget if you have one in mind.',
		'Know your timeline or budget? Add it in.',
		'Deadline and budget are handy too, if you have them.',
		'If you’re on a schedule or budget, tell me that too.',
		'Got a target date or a budget range? Toss it in.',
		'Any limits on time or budget? Good to know early.',
		'A deadline or budget, if you have one, helps a lot.',
		'Feel free to add your timeline and budget too.',
		'When do you need it, and roughly what’s the budget? Only if you know.',
		'Share a deadline or budget if there is one.',
		'Timeline or budget in mind? Add it here too.',
		'If you have a date or budget to hit, include it.'
	],

	/** Where to write back. */
	where: [
		'Got it. Where should I write back?',
		'Thanks! What’s the best email to reach you?',
		'Got it. What email should I reply to?',
		'Great, thanks. Where should I send my reply?',
		'Thanks for that. What’s your email?',
		'Perfect. Which email should I use to get back to you?',
		'Got it, thanks. Where can I reach you?',
		'Sounds good. What’s the best email for you?',
		'Thanks! Where should I reply?',
		'Great. What email should I write back to?',
		'Noted. What’s a good email for my reply?',
		'Thanks, that helps. Where should I write back?',
		'Got it. Which email works best for you?',
		'Perfect, thanks. What’s your email address?',
		'Great, I’ve got that. Where can I reply?',
		'Thanks! Drop your email and I’ll get back to you.',
		'Got it. What email should I use?',
		'Sounds great. Where should my reply go?',
		'Thanks for sharing. What’s the best email to reach you?',
		'Nice, thanks. What’s your email?',
		'Got it! Where should I send my answer?',
		'Thanks. Which email should I reply to?',
		'Great, that’s helpful. What’s your email?',
		'Understood. Where should I write back?',
		'Thanks! Leave your email and I’ll reply there.',
		'Got it. What’s the best email to get back to you on?',
		'Perfect. Where do you want my reply?',
		'Thanks, noted. What email should I use to reply?',
		'Great. Your email, so I can write back?',
		'Got it, thanks! Where can I reach you by email?'
	],

	/** The letter as Gordon will get it, and that an answer can be tapped to change it. */
	review: [
		'Here’s what I’ll get. Want to change something? Just tap it.',
		'Here’s your message as I’ll see it. Tap anything to change it.',
		'This is what lands in my inbox. Tap a message to edit it.',
		'Here’s how it’ll reach me. Anything to fix? Just tap it.',
		'Take a quick look. Tap anything you’d like to change.',
		'Here’s the message I’ll get. Tap any part to edit it.',
		'All set? Here’s what I’ll receive. Tap to change anything.',
		'Here’s what’s coming my way. Tap a message to tweak it.',
		'This is what I’ll read. Want to change something? Tap it.',
		'Quick check before it goes: tap anything to edit.',
		'Here it is, as it’ll arrive. Tap any message to change it.',
		'Looks good? Here’s what I’ll get. Tap anything to fix it.',
		'Here’s a preview. Tap one of your messages to change it.',
		'Here’s what I’ll see. Anything off? Tap it to edit.',
		'Ready to send? Here’s the message. Tap to change anything.',
		'This is it. Tap any of your messages to adjust it.',
		'Here’s what will land in my inbox. Tap to edit anything.',
		'Have a quick look. Anything to change? Just tap it.',
		'Here’s your note to me. Tap anything to change it.',
		'Here’s what I’ll receive. Edit anything by tapping it.',
		'One last look before it’s sent. Tap to change anything.',
		'Here’s the message. Want to tweak something? Tap it.',
		'This is what I’ll get. Tap any message to update it.',
		'Here’s how it reads. Tap anything to change it.',
		'Here’s what I’ll see in my inbox. Tap to edit.',
		'Almost done. Here’s the message; tap anything to change it.',
		'Here’s what gets sent to me. Tap a message to change it.',
		'Check it over. Tap anything you want to change.',
		'Here’s your message. Anything to adjust? Just tap it.',
		'Here’s what I’ll get. Tap any line to edit it.'
	],

	/** A P.S. taken in. */
	added: [
		'Got it, I’ll add that as a P.S.',
		'Added as a P.S.',
		'Got it. I’ve added that as a P.S.',
		'Nice, that’s in as a P.S.',
		'Added it to the end as a P.S.',
		'Thanks, that’s now a P.S.',
		'Done, it’s tacked on as a P.S.',
		'Got it, adding that as a P.S.',
		'Great, that’ll go in as a P.S.',
		'Noted. It’s in the P.S.',
		'Perfect, added to the P.S.',
		'Got it! That’s in the P.S. now.',
		'Thanks, I’ve put that in a P.S.',
		'Added. It’ll come through as a P.S.',
		'Sure thing, that’s in the P.S.',
		'Got it. That goes in as a P.S.',
		'All right, added as a P.S.',
		'Nice, I’ve added it to the end.',
		'Done. It’s in there as a P.S.',
		'Got it, it’s part of the P.S.',
		'Thanks! Added that as a P.S.',
		'Sounds good, it’s in the P.S.',
		'Added to your message as a P.S.',
		'Got it, that’s at the end now.',
		'Okay, that’s in as a P.S.',
		'Great, it’s added as a P.S.',
		'Noted, and added as a P.S.',
		'Got it. Tacked that on as a P.S.',
		'Perfect. That’s in the P.S.',
		'Thanks, it’s in there now as a P.S.'
	],

	/** After the ✓, once it has gone. */
	sent: [
		'Sent!',
		'Sent, thanks!',
		'All sent!',
		'Done, it’s on its way!',
		'Sent. Thank you!',
		'It’s on its way!',
		'Message sent!',
		'Sent! Thanks for writing.',
		'All done, it’s sent!',
		'Sent. Thanks for reaching out!',
		'Your message is on its way!',
		'Sent! Talk soon.',
		'Got it, and sent!',
		'Sent! Thanks so much.',
		'Done! Your message is sent.',
		'Sent. Appreciate it!',
		'On its way to my inbox!',
		'Sent! Thanks for getting in touch.',
		'All sent. Thank you!',
		'Delivered to my inbox!',
		'Sent! That’s all it takes.',
		'Sent, and thanks for the details!',
		'Done. Thanks for writing to me!',
		'Sent! Thanks for the message.',
		'Sent! Really appreciate it.',
		'It’s in my inbox now!',
		'Sent! Thanks for your time.',
		'All done! Message sent.',
		'Sent. Thanks for reaching out to me!',
		'Your note is on its way!'
	],

	/**
	 * Where and when the answer comes, in Gordon's own "usually within 1–2 days".
	 * @type {((email: string) => string)[]}
	 */
	reply: [
		(email) => `I’ll get back to you at ${email} soon. Usually within ${DAYS}.`,
		(email) => `I’ll reply to ${email}, usually within ${DAYS}.`,
		(email) => `You’ll hear from me at ${email}, normally within ${DAYS}.`,
		(email) => `I’ll write back to ${email}, usually within ${DAYS}.`,
		(email) => `Expect a reply at ${email}, usually within ${DAYS}.`,
		(email) => `I’ll be in touch at ${email}. It usually takes ${DAYS}.`,
		(email) => `I’ll answer at ${email}, typically within ${DAYS}.`,
		(email) => `Keep an eye on ${email}. I usually reply within ${DAYS}.`,
		(email) => `I’ll reply to ${email} soon, usually within ${DAYS}.`,
		(email) => `My reply will go to ${email}, usually within ${DAYS}.`,
		(email) => `I’ll get back to you at ${email}. Usually it’s within ${DAYS}.`,
		(email) => `You’ll get my reply at ${email}, most often within ${DAYS}.`,
		(email) => `I’ll email you at ${email}, usually within ${DAYS}.`,
		(email) => `I’ll follow up at ${email}, normally within ${DAYS}.`,
		(email) => `I’ll respond to ${email}, usually within ${DAYS}.`,
		(email) => `Look out for my reply at ${email}. It’s usually ${DAYS}.`,
		(email) => `I’ll reply to ${email} as soon as I can, usually within ${DAYS}.`,
		(email) => `I’ll get back to ${email} shortly, usually within ${DAYS}.`,
		(email) => `You’ll find my reply at ${email}, usually within ${DAYS}.`,
		(email) => `I’ll write to you at ${email}, usually within ${DAYS}.`,
		(email) => `Expect to hear back at ${email}, normally within ${DAYS}.`,
		(email) => `I’ll reply at ${email}. I usually get back within ${DAYS}.`,
		(email) => `I’ll send my reply to ${email}, typically within ${DAYS}.`,
		(email) => `I’ll be back in touch at ${email}, usually within ${DAYS}.`,
		(email) => `A reply is coming to ${email}, usually within ${DAYS}.`,
		(email) => `I’ll answer you at ${email}, usually in ${DAYS}.`,
		(email) => `I’ll get back to you at ${email}, most likely within ${DAYS}.`,
		(email) => `I’ll reach out at ${email}, usually within ${DAYS}.`,
		(email) => `Watch ${email} for my reply, usually within ${DAYS}.`,
		(email) => `I’ll reply to you at ${email}, generally within ${DAYS}.`
	],

	/** Before the call link, for anyone who'd rather not wait. */
	hurry: [
		'Can’t wait?',
		'In a hurry?',
		'Rather talk it through?',
		'Want to talk sooner?',
		'Prefer a quick call?',
		'Easier to chat live?',
		'Need it sooner?',
		'Would a call be easier?',
		'Short on time?',
		'Rather talk than wait?',
		'Want to speed things up?',
		'Keen to get started?',
		'Prefer to talk it over?',
		'Want to skip the wait?',
		'Easier to explain out loud?',
		'Time-sensitive?',
		'Rather hop on a call?',
		'Want to go over it together?',
		'Need a faster answer?',
		'Prefer talking to typing?',
		'Want to move quickly?',
		'Rather discuss it live?',
		'Eager to chat?',
		'Got more to say?',
		'Want to walk me through it?',
		'On a tight timeline?',
		'Like to talk first?',
		'Rather not wait for email?',
		'Want a quicker chat?',
		'Easier over a call?'
	],

	/** A send that failed. */
	oops: [
		'Hmm, that didn’t go through. Sorry about that!',
		'Oops, that didn’t send. Sorry!',
		'Hmm, something went wrong on my end. Sorry!',
		'That didn’t go through, sorry about that.',
		'Sorry, the message didn’t send.',
		'Hmm, it didn’t send. My apologies!',
		'Something got stuck. Sorry about that!',
		'Oh no, that didn’t go through.',
		'Sorry, something went wrong there.',
		'Hmm, that one didn’t make it. Sorry!',
		'Looks like it didn’t send. Sorry about that.',
		'Sorry! The message didn’t get through.',
		'Hmm, that failed to send. Sorry!',
		'Oops, something broke on my side.',
		'That didn’t work, sorry!',
		'Sorry, my inbox didn’t get that one.',
		'Hmm, the send didn’t work. Sorry!',
		'Something went wrong sending that. Sorry!',
		'Oops! That didn’t go through.',
		'Sorry, it didn’t send this time.',
		'Hmm, that hit a snag. Sorry!',
		'Apologies, that didn’t send.',
		'That didn’t make it through, sorry.',
		'Hmm, no luck sending that. Sorry!',
		'Sorry about this, it didn’t send.',
		'Oops, the message got stuck.',
		'Hmm, something’s not working. Sorry!',
		'That didn’t send, and that’s on me. Sorry!',
		'Sorry! Something went wrong with sending.',
		'Hmm, it didn’t go through. Sorry for the hassle.'
	],

	/**
	 * What to do then, before the Copy message button.
	 * @type {((email: string) => string)[]}
	 */
	retry: [
		(email) => `Try again? Or copy your message and email it to me at ${email}.`,
		(email) => `Mind trying again? Or copy your message and send it to ${email}.`,
		(email) => `Give it another go, or copy your message and email ${email}.`,
		(email) => `Try once more? You can also copy it and email me at ${email}.`,
		(email) => `Please try again, or copy your message and email it to ${email}.`,
		(email) => `Try sending again? Or email your message to ${email}.`,
		(email) => `One more try? Or copy it over to ${email}.`,
		(email) => `Want to retry? Or copy your message and write to ${email}.`,
		(email) => `Try again in a moment, or email your message to ${email}.`,
		(email) => `You can retry, or copy the message and email ${email}.`,
		(email) => `Try again? If it still won’t go, email it to ${email}.`,
		(email) => `Another try might work. Or copy it and email ${email}.`,
		(email) => `Retry below, or copy your message and send it to ${email}.`,
		(email) => `Try again, or paste your message into an email to ${email}.`,
		(email) => `Let’s try again. Or copy it and email me at ${email}.`,
		(email) => `Try once more, or send it straight to ${email}.`,
		(email) => `Give it another shot, or email your message to ${email}.`,
		(email) => `Try again? Or copy your words and email ${email}.`,
		(email) => `Hit try again, or copy it and email me at ${email}.`,
		(email) => `Please retry, or email your message to ${email}.`,
		(email) => `Try again soon, or copy your message and email ${email}.`,
		(email) => `Another go? Or copy your message and email ${email}.`,
		(email) => `Try again, or copy and email it to ${email}.`,
		(email) => `Maybe try again? Or email me directly at ${email}.`,
		(email) => `Try one more time, or copy it and write to ${email}.`,
		(email) => `Retry, or copy your message and email it to ${email}.`,
		(email) => `Try again? You can also email it to ${email}.`,
		(email) => `Give it another try, or copy it and email ${email}.`,
		(email) => `Try again, or send your message to ${email} by email.`,
		(email) => `Try once more? Or copy it and email me at ${email}.`
	]
};

/** One wording of each line, for one visit's chat. */
export const draw = () =>
	/** @type {{ [K in keyof typeof lines]: (typeof lines)[K][number] }} */ (
		Object.fromEntries(Object.entries(lines).map(([key, list]) => [key, list[Math.floor(Math.random() * list.length)]]))
	);
